### PR TITLE
Changes to testNEST.cpp for use with nestpy

### PR DESCRIPTION
**Pull request by infophysics**
Relegated the main() function to an actual function called testNEST which can be wrapped using python.  after compiling, testNEST still works the same way as before in the terminal.

### CODE REVIEW

**Comment by tunnell** [comment]
Matthew, can we include in release?  It's just renaming main to testNEST to help with bindings?

**Comment by infophysics** [comment]
Let me know if I can help in any way.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mszydagis** [comment]
I don't know how to fix the conflict. I don't understand how git displays it (used to svn's way still, even after all these years). Nick, can you please help resolve?

**Comment by tunnell** [comment]
Replaced by #31.

**Pull request closed without merging**
