### PR TITLE
Update the project version

### PR DESCRIPTION
**Pull request by riffard**
Updating the project version to avoid future confusion

### CODE REVIEW

**Comment by mszydagis** [comment]
Quentin, by the time this is fully released we will be up to 2.2.4, so maybe it is best to put that not 2.2.3?? I don't know..

**Comment by riffard** [comment]
It's still 2.2.3 has this is the latest tag.

**Comment by riffard** [comment]
An alternative is to let git set the version: 
```
###############        Get version from git        #####################
execute_process(COMMAND git describe
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE PROJECT_GIT_VERSION
        OUTPUT_STRIP_TRAILING_WHITESPACE)

function(get_versions versionString version)
    if ("${versionString}" STREQUAL "")
        set(version "0.0.0" PARENT_SCOPE)
        return()
    endif ()

    string(REGEX REPLACE "([0-9]*)([.][0-9]*[.][0-9]*-?.*)$" "\\1" numbers ${versionString})
    set(major ${numbers})
    string(REGEX REPLACE "([0-9]*[.])([0-9]*)([.][0-9]*-?.*)$" "\\2" numbers ${versionString})
    set(minor ${numbers})
    string(REGEX REPLACE "([0-9]*[.][0-9]*[.])([0-9]*)(-?.*)$" "\\2" numbers ${versionString})
    set(patch ${numbers})
    set(version "${major}.${minor}.${patch}" PARENT_SCOPE)
endfunction()

get_versions("${PROJECT_GIT_VERSION}" version)
set(PROJECT_GIT_VERSION ${version})
```

**Comment by mszydagis** [comment]
ok, can you add that?

**Comment by riffard** [comment]
Done

**Pull request merged**
