### PR TITLE
Minor fixes for 2.1.0

### PR DESCRIPTION
**Pull request by kreczko**
## Fixed typo for MIN_ROOT_VERSION
In !59 I accidently introduced a typo when specifying the MIN_ROOT_VERSION for the examples, thus rendering the variable useless.

Now fixed, and the MIN_ROOT_VERSION should now work as expected.

## Reduce CMake minimal version

Depending on the OS (e.g. SL6) only older CMake versions might be available.
For that reason reduced the minimal version from 3.12 (driven by travis-ci) to 3.8 (driven by used CMake features)

## Position independent code (WIP)

While it is possible to build shared libraries linking against a static NEST library, one will run into issues. To fix that, enabled Position Independent Code (PIC) option for NEST.

### CODE REVIEW

**Comment by mszydagis** [comment]
my apologies Luke, I'm very very very sorry but I cannot approve this at this time -- I already tagged the release late last night, as you probably saw, and I don't want to confuse people and shake faith in NEST stability by having a change already in the master branch the day after, making the bleeding-edge better than the last tagged release less than 24 hours later. I will approve this of course, but eventually, please let's give it a little bit of time. This won't make a big difference since most people will be up-to-date enough on their ROOT versions anyway. 

However, as you have already created this request, you could perhaps also correct the typo in the README that says the min CMAKE version needed is still 2 . something? Again, I will approve this but not today since it will cause massive confusion: I just advertised the release to everyone on LZ, LUX, DARWIN, nEXO, XENON a few hours ago.

**Comment by mszydagis** [comment]
thank you, @kreczko , and sorry again I cannot merge this immediately. There are already papers coming citing the tagged version haha. I will keep this merge or pull request open.

**Comment by kreczko** [comment]
Added to README and updated minimal version to 3.8 as a result of our discussion yesterday.

As for the merge policy, that's up to you, take your time if you need it.

From a release standpoint, such small changes should probably go into 2.1.1.
Please let me know when you find other issues.

**Comment by kreczko** [comment]
@mszydagis sorry for the delay, the scripts have now been included (5952e75):
 - `220RnCalib.sh` &rarr; `220RnCalib.in` (CMake template)
 - `loopNEST.sh` &rarr; `loopNEST.in` (CMake template)
 - `bin/bash` &rarr; `/usr/bin/env bash` 
 - CMake sets absolute paths to `testNEST` and `rootNEST` in the scripts during `cmake` call
 - scripts are installed into `<install dir>/bin` during `make install` and have the correct permissions

image

**Pull request merged**
