### PR TITLE
Model case refactor

### PR DESCRIPTION
**Pull request by jpbrodsky**
This branch breaks out the different cases in GetYields into their own virtual class methods. This has the advantage of allowing a user to override individual parts of the model without hard editing the NEST code.

### CODE REVIEW

**Comment by mszydagis** [comment]
hi Jason, this looks beautiful. I have only a couple minor comments (and one more major, requiring more review) before I can merge and close. I also wanted to ask if you will be doing your detector class re-dressing now if we wait a few more weeks for next release, or should we continue to put it off? I'd like to get us to point where code structure complete and good enough (physics-only focus)

* Lots of NexONi = alpha (0.05*energy) repeated all over the place, perhaps can "globalize" somehow? (At least the 0.05 as a variable that can change this for all particle types for which relevant all at once). Seems a bit too repetitive, more so, and thus less efficient now.  

* In NEST.hh comments, not quite right: Beta/Photoelectric case should be Beta/Compton/etc. while Gamma is Gamma/Photoelectric/X-ray. (In future, we will also distinguish ER capture, IC, Auger, etc., but not for now, hence the "etc.")

@justinjmueller @Aspelene  Should comment on whether this will make things better/easier for naturally incorporating liquid Argon as another element now (eventually, He and Ne as well, down the line..) Perhaps an extra argument for the atomic number of substate? (Currently just a #define statement called ATOM_NUM in include/NEST.hh header file) Might be time sooner rather than later to bring over any LAr forks/branches people are using (I see none officially on here, not ideal!) 

Lastly, not entirely related, but as a member of EXO can you comment on my newer solution for W problem, which I saw you did not disturb, of course. Dan McK pointed out that not only was my previous suggested solution artificially wiggly in key region, but doesn't address fact that only light yield was much higher not charge from EXO. So I added extra photons (they may be IR in SiPMs??)

**Comment by jpbrodsky** [comment]
> NexONi = alpha (0.05*energy)

Yes, we can make this another class function that can be overridden, or make the 0.05 a member variable that can be overridden by itself.
The first option is more flexible (the user could set NexONi to literally anything), but a touch clunkier. The second is simple if we want to just make the 0.05 adjustable. I'm not sure which is more useful to users.

> Comments
I'll adjust.

> Argon
Let's avoid #DEFINE as much as possible going forward, and migrate some of the existing #DEFINEs for user-set parameters to the detector class or similar. Our goal should be that a user can lay their customization on top of NEST without editing the NEST code--that way, they can easily grab updates to NEST without having to manually resolve conflicts. #DEFINEs will definitely require the user to edit the NEST code.

I'd probably need to take a look at what argon-specific model calculations look like before having a specific suggestion. A lot depends on how much changes--if it's the whole functional form, it may make sense to have entirely separate methods for argon (e.g. GetYieldBetaArgon), to help users read the argon-specific code more easily. If the functional form is largely the same and just a few numbers are tweaked, we could maybe just add some input parameters to the functions.

> Detector class

I probably won't address this in the next few weeks, sadly. We shouldn't hold up any releases for this. I'll try and squeeze at least a few changes in if I have time.

> EXO-related W change
I've received the scripts used to make the EXO-200 paper and am setting them up to hook into NEST so I can remake those plots with NEST updates. I'll let you know once I have that done.
The sentiment from people I've talked to on EXO-200 is that they'd be more reassured by the density dependence if they saw the fit to more than two points. Is that a plot we can make right now, or is there a shortage of really reliable W measurements at densities other than EXO-200 and whatever Dahl was using?

Best,
Jason
________________________________

**Comment by justinjmueller** [comment]
I don't know that we should count on the models for argon being exactly the same functional form. The NR model will only be different by at most one additional parameter. I think Kate knows best about the ER models, but I'm pretty sure that the models she had the most luck with are based on the gamma sigmoids for xenon. Honestly I think we can force them to be the same functionally, though that might be difficult for ER. Most likely we'll want to hear from @Aspelene on this.

**Comment by Aspelene** [comment]
ER argon model isn't very different from ER xenon model (Justin is right - we based it on gamma sigmoids), and we have only two additional parameters compared to xenon model. But the values of other parameters is very different compared to xenon, and I think it'll be easier to make separate methods for at least ER argon model (beсause otherwise we must to parametrize 15+ values).

**Comment by mszydagis** [comment]
For Nex/Ni literally anything would be great because in some models it even has opposite trend of what we have now, so maximum flexibility for its energy dependence is desirable, not just a 1-number change.

For my many #DEFINE’s I was trying to restrict to things that change “rarely” (like typically people use only xenon or only argon) but you’re point about manual merging after an update is well taken. One thing at a time, though, let’s leave what I have right now and address your current existing merge request. 

Argon: based on the further feedback from Justin and Kate, and thinking about things more, I would like to suggest that we leave the functions like you have it, and add an additional option with the ‘Z’ of the element. That way, if functions stay the same then great, and then if as J & K said not always, then an if statement inside these functions should suffice. I like this better than yet more functions, so I don’t them to proliferate so much. Modularity is great and all, but then there is overkill. What if we add neon, helium, hell even krypton some day?? : - )

Detector class etc.: don’t sweat it, but you have time, because Chris is really busy the next weeks due to DANCE conference etc., so we may delay more. I asked him to re-do the file names and structure again, as per our discussion last phone meeting and other open git issue. Instead of outsourcing to someone else to do, I’d like to wait bit more.

Work function: The fit is definitely to more than 2 points in density, because we have solid also agreeing more with EXO-200 as I showed. However, this is moot now because Dan is not happy with my density solution. I am still revising the density dependence, but using e- instead of mass as you yourself and others had also suggested makes my wiggle at ~3 g/cm^3 look like an even worse joke now. There is also the fact I mentioned that EXO agrees well on charge yield, but not light. 

So, instead I have just added a lot more photons (35% to be exact). Please take a look at this newer solution, in the code on the master branch right now, not my original one I suggested in meetings and by e-mail. I will be present on it tomorrow afternoon as well.  Note: because of the difference in light but not charge I am now much more highly suspicious of possibility that perhaps old 13.7 eV measurement was wrong/off in some way. Dave Moore had told me “oh, just move g1 and g2 up or down together” Problem is it’s not together. And now matter how badly we messed up I guarantee you our g1 was not off by 35%. I also found a Bolotnikov measurement at EXO’s density claiming 12.9 eV using a Cs-137 662 keV gamma-ray source, but with no errors bars and lots of interpretation. This is a summary of where things stand now.

Once you’ve fixed the comment and Nex/Ni I will re-review :) and approve request. Everything else is separate issue (Kate, 15+ values fine, we can make vector like for NR)

**Comment by jpbrodsky** [comment]
I've done the other fixes and sent them straight into master since I think Matthew accidentally approved the merge too early.

**Comment by YaniBion** [comment]
Hi, I'm sorry if this is not the proper thread.
Is there any available reference for the dependence of the work function with density? I'm quite surprised by this change, as the work function is not something that I would relate to a macroscopic quantity as density. Is it a screening effect?
I would be very thankful for any help on this.

**Comment by sophiaandaloro** [comment]
Hey @jpbrodsky not sure if you'll see this now, or if Matthew can help either but do you have any reference for the NexONi ratio function? thank you!

**Comment by mszydagis** [comment]
@grischbieter actually created it, not Jason, if you referring to its ERF energy dependence? He did it under my direction to match several data sets, while rolling it off to 0 at 0 energy, to explain the huge increase in Qy. The high energy value of ~0.2 comes from Doke 2002 (where he tried to explain discrepancy with 0.06, but that's for gas, so that's why). Wow, the "git blame" function really does not seem to work! :(

**Comment by sophiaandaloro** [comment]
Ok, thank you for helping me track down the real blame. So I assume the constants are just minimized with all available NexONi data that Greg had?

**Pull request merged**
