### PR TITLE
Gr multiple scatter

### PR DESCRIPTION
**Pull request by grischbieter**
I've created a similar tool to doubleScatter.cpp, now multipleScatter.cpp. 

It has the same usage pretty much, with one more command line argument for "nScatters" per event. 
If "-1" is provided for nScatters, a random draw using a falling exponential is used. This can likely be changed in the future to match some real physics, but right now its just a simple exponential to give some variety.

Just like doubleScatter.cpp, two files can be provided, where the second file is used for the last scatter of each event. 
Tests worked well, and I was able to reproduce the results of doubleScatter.cpp.

README has been updated. We may want to remove doubleScatter.cpp, since this new tool can all the same things and more. But I'll let that decision be made later.

### CODE REVIEW

**Comment by mszydagis** [comment]
hi @grischbieter  I agree to not confuse everyone -- please can you remove all traces of double scatter then and just leave the multiple scatter code, assuming you checked they're absolutely identical results for N=2?  Thanks!!

**Comment by grischbieter** [comment]
Alright @mszydagis , that's been taken care of and all builds have passed. I think this is ready to merge unless there's anything else you can think of adding/removing.

**Comment by mszydagis** [comment]
@grischbieter  Almost there, Greg, just a few final comments before I can approve the merge request:  you still have the world "double" and refer to the original cpp file name in your new multiple scatter code, up top, in multiple places. So that's a very minor thing but you should clean that up. Secondly, rand_exponential(1., 1.5, 50.) appears in at least 2 places but the numbers are not justified, where do they come from?? Write a brief comment at least perhaps.

**Comment by grischbieter** [comment]
Good catch -- sorry about that. Those mentions to doubleScatter.cpp leftover from copy/paste have been removed. 

The inputs to the rand_exponential generator are just to give a quick approximation to the number of scatter produced in typical LXe events, which is usually just a handful of scatters; a "halfLife" of one scatter provides a decent spread, and the min/max number of scatters is a wide window between 2-50, although the exponential falls well before 50 scatters. I've given these variable names in the code, making it clearer how users can edit things for better flexibility.

**Pull request merged**
